[auth]
shared_password = "change-me"  # optional simple gate; leave empty to disable

[models]
chatgpt5_api_key = "sk-..."
claude_api_key = "sk-ant-..."
gemini_api_key = "AIza..."
grok_api_key = "xai-..."

[app]
db_path = "icu_llm_arena.db"
